import fasttext

model = fasttext.load_model("trained_models/model_1.bin")

# 1. Predict a single song lyrics
text_to_predict = "Dắt cho em đi chơi Ta về quê nơi bình yên Nơi lúa xanh ngập trời Chẳng cần lo những muộn phiền Tình mình càng thêm thắm tươi Như bài ca anh hát Cây trái đơm hoa nở bông Khi có em bên đời Cô bác nơi đây thân thương Hay nhìn em nên đừng lo Lâu lâu thấy cô gái đẹp Lại còn hiền họ tò mò Mùa này có em ở đây Do bội thu trúng lúa Má hứa sang năm Sẽ rước em về nhà Gà chưa gáy anh đã dậy ra đồng Tháng mười nước nổi Cá ngập tràn trên bờ sông Miền quê anh Sương gió nhưng mặn mà Nơi mà anh lớn lên Từng ngày với dân ca Rặng dừa xanh bóng lá che mát đầu Ba má đã coi ngày tốt Rước em về để làm dâu Cánh lục bình trôi Theo dòng nước xuôi dòng Hai đứa mình thương nhau Họ hàng cũng vui lòng Dắt em đi giăng câu Về nấu tô canh bầu Chiều chiều cái lẩu kho tiêu Anh ngồi chill với mấy cậu Anh nói là ai cũng tốt Thiệt thà mà dễ thương Kính rượu phải dâng hai tay Không sai là lễ thường Mấy ổng xỉn, mấy ổng say Bà con ở đâu cũng kể hết Nhưng mà tỉnh là ra đồng ngay Chứ không cái kiểu nhậu bê bết Thiệt là quý lắm mới được ngồi Nghe câu chuyện thời xa xưa Chú Tám nói thôi được rồi Tới vòng của mày đã qua chưa Cuộc đời có mấy khi vui Về đây với anh ta dựng xây tình nồng Lòng vòng mà chi chán lắm em ơi Anh Ba ổng có thêm thằng ku tí rồi Được mùa anh cưới em luôn Ngày qua rước dâu Anh đón em bằng xuồng Mà chèo xuồng là đậm chất quê luôn Hứa bên em ngày sau không để em buồn Thành thị mình đưa đón nhau bằng xe Chứ còn mà về quê Anh chỉ thích đi bằng ghe Anh có nhiều kỉ niệm thời tuổi trẻ Thôi cứ để từ từ Rồi anh kể cho em nghe Nước đứng rồi mình thả tay lưới Cá mình gỡ sẽ mỏi tay Tranh thủ hái ngó lục bình Về chấm mắm kho là hết sảy Chút nữa dắt em đi sang đồng Rồi mình bắt ốc về kho tiêu Món này miền Tây quê anh Ai mà không biết là thương hiệu Miền quê anh cây trái ngọt lành Nổi danh miệt vườn sông Cửu Long Đất nhà anh thì không có nhiều Chỉ vài chục công nhưng đủ rộng Tía ổng trồng được mấy vườn xoài Thu hoạch quanh năm cũng đủ sống Thử suy nghĩ đến chuyện sang năm Em có muốn làm bà chủ không Về má dạy cho em Làm hết mấy món đặc sản miền Tây Món anh ăn hồi còn nhỏ xíu Đến khi lớn lên từng ngày Cao hương mỹ vị đất khách quê người Sao bằng ở đây Tình thân thương mái ấm gia đình Vẫn luôn đong đầy Dắt cho em đi chơi Ta về quê nơi bình yên Nơi lúa xanh ngập trời Chẳng cần lo những muộn phiền Tình mình càng thêm thắm tươi Như bài ca anh hát Cây trái đơm hoa nở bông Khi có em bên đời Cô bác nơi đây thân thương Hay nhìn em nên đừng lo Lâu lâu thấy cô gái đẹp Lại còn hiền họ tò mò Mùa này có em ở đây Do bội thu trúng lúa Má hứa sang năm Sẽ rước em về nhà Cuộc đời có mấy khi vui Về đây với anh ta dựng xây tình nồng Lòng vòng mà chi chán lắm em ơi Anh Ba ổng có thêm thằng ku tí rồi Được mùa anh cưới em luôn Ngày qua rước dâu Anh đón em bằng xuồng Mà chèo xuồng là đậm chất quê luôn Hứa bên em ngày sau không để em buồn"

prediction = model.predict(text_to_predict, k=-1, threshold=0.01)

print(f"Prediction for '{text_to_predict}':")
print(prediction) 